import styles from "../styles/Home.module.css";
import type { ReactNode, FC } from "react";
import Head from "next/head";
import { Box } from "@mui/material";
import { useRouter } from "next/router";
import Navbar from "./Navbar";

type Props = {
  children: ReactNode;
};

const Layout: FC<Props> = ({ children }) => {
  const { pathname } = useRouter();

  return (
    <Box>
      <Head>
        <title>React-Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {pathname === "/login" ? null : <Navbar />}
      <main className={styles.main}>{children}</main>
    </Box>
  );
};

export default Layout;
